### ISSUE TITLE
Dialog not showing again once moved to sdk33.1.198

### ISSUE THREAD

**Issue by muxame** [distriqt/ANE-Debug#3]
Hello ,

After upgrading to Harman SDK 33.1.198 . The dialog stopped showing on Intellij Idea AS3 Air project .

I spent the last 2 days trying to make it work but it's not working, no errors at the log or anything. I tried all possible ways, still the dialog not showing . no code changes have been made . i only upgraded to the latest ANE and latest AndroidX Anes and Core Any following exactly your documentation 

Please kindly can you send a working sample project for Intellij Idea for adobe air or guide me how to find and fix this issue .

at the same project i have :- 
Vibrate Ane working
Facebook Ane working
In App building working 
Dialog Ane not working 

my device is android 10.

**Comment by distriqt-developer** [comment]
Please post in the Dialog extension:

https://github.com/distriqt/ANE-Dialog/issues/new
